// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Vb2mdr_vfiyfpVvUvFEgumSXny9sqqA',
    appId: '1:191423138664:web:786a9c4d379aa144d324dd',
    messagingSenderId: '191423138664',
    projectId: 'task-manager-luan',
    authDomain: 'task-manager-luan.firebaseapp.com',
    storageBucket: 'task-manager-luan.firebasestorage.app',
    measurementId: 'G-K7V9VZNYW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD85HjoLSKH9fqQG_jCOT9t0t5N4wpSjnA',
    appId: '1:191423138664:android:e7e73257f38921e4d324dd',
    messagingSenderId: '191423138664',
    projectId: 'task-manager-luan',
    storageBucket: 'task-manager-luan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsjGQsx734yZMz94bu5esa03H1oZx2ADQ',
    appId: '1:191423138664:ios:80e47fbc11d86318d324dd',
    messagingSenderId: '191423138664',
    projectId: 'task-manager-luan',
    storageBucket: 'task-manager-luan.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsjGQsx734yZMz94bu5esa03H1oZx2ADQ',
    appId: '1:191423138664:ios:80e47fbc11d86318d324dd',
    messagingSenderId: '191423138664',
    projectId: 'task-manager-luan',
    storageBucket: 'task-manager-luan.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-Vb2mdr_vfiyfpVvUvFEgumSXny9sqqA',
    appId: '1:191423138664:web:1e8e3fdc98dfefa7d324dd',
    messagingSenderId: '191423138664',
    projectId: 'task-manager-luan',
    authDomain: 'task-manager-luan.firebaseapp.com',
    storageBucket: 'task-manager-luan.firebasestorage.app',
    measurementId: 'G-6EXCZGK4ZY',
  );
}
